version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meine_postgres_db
    environment:
      POSTGRES_USER: use
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: meine_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
